/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatpageIndexRouteImport } from './routes/chatpage/index'
import { Route as ChatpagePageIdRouteImport } from './routes/chatpage/$pageId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatpageIndexRoute = ChatpageIndexRouteImport.update({
  id: '/chatpage/',
  path: '/chatpage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatpagePageIdRoute = ChatpagePageIdRouteImport.update({
  id: '/chatpage/$pageId',
  path: '/chatpage/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chatpage/$pageId': typeof ChatpagePageIdRoute
  '/chatpage': typeof ChatpageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chatpage/$pageId': typeof ChatpagePageIdRoute
  '/chatpage': typeof ChatpageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chatpage/$pageId': typeof ChatpagePageIdRoute
  '/chatpage/': typeof ChatpageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chatpage/$pageId' | '/chatpage'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chatpage/$pageId' | '/chatpage'
  id: '__root__' | '/' | '/chatpage/$pageId' | '/chatpage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatpagePageIdRoute: typeof ChatpagePageIdRoute
  ChatpageIndexRoute: typeof ChatpageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatpage/': {
      id: '/chatpage/'
      path: '/chatpage'
      fullPath: '/chatpage'
      preLoaderRoute: typeof ChatpageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatpage/$pageId': {
      id: '/chatpage/$pageId'
      path: '/chatpage/$pageId'
      fullPath: '/chatpage/$pageId'
      preLoaderRoute: typeof ChatpagePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatpagePageIdRoute: ChatpagePageIdRoute,
  ChatpageIndexRoute: ChatpageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
