/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChatpageIndexRouteImport } from './routes/chatpage/index'
import { Route as ChatpagePageIdRouteImport } from './routes/chatpage/$pageId'
import { Route as ChatChatIdRouteImport } from './routes/chat/$chatId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatpageIndexRoute = ChatpageIndexRouteImport.update({
  id: '/chatpage/',
  path: '/chatpage/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatpagePageIdRoute = ChatpagePageIdRouteImport.update({
  id: '/chatpage/$pageId',
  path: '/chatpage/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatChatIdRoute = ChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chatpage/$pageId': typeof ChatpagePageIdRoute
  '/chatpage/': typeof ChatpageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chatpage/$pageId': typeof ChatpagePageIdRoute
  '/chatpage': typeof ChatpageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/chat/$chatId': typeof ChatChatIdRoute
  '/chatpage/$pageId': typeof ChatpagePageIdRoute
  '/chatpage/': typeof ChatpageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/chat/$chatId'
    | '/chatpage/$pageId'
    | '/chatpage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/chat/$chatId'
    | '/chatpage/$pageId'
    | '/chatpage'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/signin'
    | '/signup'
    | '/chat/$chatId'
    | '/chatpage/$pageId'
    | '/chatpage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ChatChatIdRoute: typeof ChatChatIdRoute
  ChatpagePageIdRoute: typeof ChatpagePageIdRoute
  ChatpageIndexRoute: typeof ChatpageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatpage/': {
      id: '/chatpage/'
      path: '/chatpage'
      fullPath: '/chatpage/'
      preLoaderRoute: typeof ChatpageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chatpage/$pageId': {
      id: '/chatpage/$pageId'
      path: '/chatpage/$pageId'
      fullPath: '/chatpage/$pageId'
      preLoaderRoute: typeof ChatpagePageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$chatId': {
      id: '/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ChatChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ChatChatIdRoute: ChatChatIdRoute,
  ChatpagePageIdRoute: ChatpagePageIdRoute,
  ChatpageIndexRoute: ChatpageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
